### ISSUE TITLE
Chinese translation on all English files for testmap

### ISSUE THREAD

**Issue by Blueberryy** [Whimsyduke/SC2_GameTranslater#1]
https://github.com/Whimsyduke/SC2_GameTranslater/blob/9a5c8878ae6cdf1507710b8407f3d69fbc5353d1/TestMap/TranslateMod.SC2Mod/enUS.SC2Data/LocalizedData/GameStrings.txt#L1

**Comment by Whimsyduke** [comment]
It is just a map for test, so it is a untranslated map.
